version: '3.8'

services:
  php:
    build: .
    ports:
      - "8040:8000"
    volumes:
      - .:/app
    environment:
      SUPABASE_DB_URL: "postgresql://postgres.yzwwmawjpvvljuevdohw:maxit2025@aws-0-eu-west-3.pooler.supabase.com:5432/postgres"
